### ISSUE TITLE
Create a Runnable to copy a template repo into a new repo

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#113]

**Comment by bastienterrier** [comment]
https://github.com/Zenika/Formation--Modele/wiki

**Comment by EmmanuelDemey** [comment]
This feature will be only available when the user install the project on his own server. 

Here is a quick reminder of the commands we should exectute : 

```
git clone http://repo to copy
rm -Rf .git
git init
git remote add origin http://new repo
git add .
git commit -m "First Commit"
git push origin master
```

**Comment by bastienterrier** [comment]
Closed: added by Github on new Repo
