### ISSUE TITLE
Create a VSCode plugin for autocompletion in rules.yml

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#119]
It would be great to create a VSCode plugin to get autocompletion when editing the `rules.yml` file with Rules and Runnables.

**Comment by bastienterrier** [comment]
https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by EmmanuelDemey** [comment]
We can maybe give Schemastore a try ? http://schemastore.org/json/
