### ISSUE TITLE
Add the support of CRON jobs

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#124]

**Comment by EmmanuelDemey** [comment]
New ideas : 
- [x] possibility to send as a body an array of configuration object
- [x] For one configuration object, give the possibility to define an array of files
- [x] The Cron pattern should be defined in the .yml configuration file.
- [ ] Limit the number of calls per project
- [x] Check the Cron pattern . For example, a pattern like `every second` should not be allowed.

**Comment by bastienterrier** [comment]
- [x] Check rules-cron-*.yml file size
