### ISSUE TITLE
Create a CLI for executing our rules

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#16]
In order to make our rules useable on the developer device, we can maybe create a command line interface ?

**Comment by bastienterrier** [comment]
Can we close/remove this issue?

**Comment by EmmanuelDemey** [comment]
We can remove the priority for the moment

**Comment by bastienterrier** [comment]
https://github.com/DX-DeveloperExperience/git-webhooks-tester
