### ISSUE TITLE
Still "default" displayed as the bot name

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#212]
![image](https://user-images.githubusercontent.com/555768/59012604-3af21300-8838-11e9-94fe-7f63f6a595df.png)

**Comment by EmmanuelDemey** [comment]
![image](https://user-images.githubusercontent.com/555768/59018699-c672a080-8846-11e9-9c1b-96d8519f5034.png)

**Comment by bastienterrier** [comment]
Must be a cache issue
