### ISSUE TITLE
Send Review for a PR hook

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#215]
By default, we should be able to send review on a PR in order to check its name .

![image](https://user-images.githubusercontent.com/555768/59019166-cb841f80-8847-11e9-8abe-b62588c56ebe.png)

**Comment by bastienterrier** [comment]
https://developer.github.com/v3/pulls/reviews/#submit-a-pull-request-review

**Comment by bastienterrier** [comment]
A Github status is linked to a Commit
![image](https://user-images.githubusercontent.com/25296454/59035247-27ad6a80-886d-11e9-80cb-cdd654234f91.png)
