### ISSUE TITLE
Add the tool to project-starter project

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#220]

**Comment by bastienterrier** [comment]
Is this issue related to Git-Webhooks or project-starter ?

**Comment by EmmanuelDemey** [comment]
We can say both. 
As project-starter is currently in development, it will be a very good use case for testing our tools

**Comment by bastienterrier** [comment]
ping @ig1na

**Comment by bastienterrier** [comment]
https://github.com/DX-DeveloperExperience/project-starter/issues/91
