### ISSUE TITLE
Add npm audit in Circle CI

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#49]

**Comment by quinnturner** [comment]
Hi there, consider using a package that I maintain for this: [IBM/audit-ci](https://github.com/IBM/audit-ci).

**Comment by EmmanuelDemey** [comment]
Why not using directly `npm audit`. Our CI use npm, we do not need support for yarn .

**Comment by quinnturner** [comment]
You can control what happens in the CI environment based on the result of an audit. For example, preventing integration if vulnerabilities are found above a configurable level (`low`, `moderate`, `high`, `critical`), excluding whitelisted modules or advisories. Also, you can show more (or less) detailed reports.
