### ISSUE TITLE
Post Actions - Deploy on Github / Gitlab pages 

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#54]
- [x] Github
- [ ] Gitlab ==> Waiting for API updates

**Comment by bastienterrier** [comment]
Deploy on gh-pages <=> merge current -> gh-pages, isn't @EmmanuelDemey ?

**Comment by EmmanuelDemey** [comment]
Mmm I did not understand :)

The use case is to be able to push to the gh-pages a subdirectory of another branch (the default one as an example)

**Comment by bastienterrier** [comment]
Ok, thank's

**Comment by bastienterrier** [comment]
4 steps to deploy FOLDER into BRANCH:
- get content: GET /repos/owner/repo/contents/FOLDER
- create tree: POST /repos/owner/repo/git/trees
```json
{"tree": [
  {
    "path": "docs/.vuepress",
    "type": "tree",
    "mode": "040000",
    "sha": "c929b0ba4e0b9210afd0f6c175e43bf10eb011e9"
  },
  {
    "path": "docs/README.md","type": "blob","mode": "100644",
    "sha": "b34b0da1ffedbb2359066ad1e6e2082ce1c92cd9"
  },
  {
    "path": "docs/guide","type": "tree","mode": "040000",
    "sha": "73aa7dc3a52db1d1f25dc74f8a870ecc5ea9a0e4"
  },
  {
    "path": "docs/rules","type": "tree","mode": "040000",
    "sha": "05d81ba237aa6263524d138f1668ea2e71e38ecb"
  }
]}
```
- create commit: POST /repos/owner/repo/git/commits
```json
{
	"message": "commit to gh-pages",
	"tree": "07b8b9c2b25b8b32181e72467cdaac2e2894ceed"
}
```
- update ref: PATCH /repos/owner/repo/git/refs/heads/BRANCH
```json
{
	"sha": "10eb5cdabac18bfaa9345a254f08f42023a357db",
	"force": true
}
```

**Comment by bastienterrier** [comment]
Gitlab API does not allow to commit a tree sha
