### ISSUE TITLE
Rename everyting related to Stack

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#83]
I think we use the wrong term for our object. 
We should rename/remove (variables, methods, objects, ...) everything related to Stack. 
For example @StackRegister should be rename @RuleRegister, the Stack interface into Rule, ...

The name of our rules should be more explicit. 
- For the rule about semver, we can give the name "exact-npm-version`
- For the rule about tslint, we can give the name "ts-lint`
The name of the file should be same : `exact-npm-version.ts` and `ts-lint.ts`

**Comment by bastienterrier** [comment]
Not my project... :)
@ig1na

**Comment by EmmanuelDemey** [comment]
oups
