### ISSUE TITLE
Possibility to rerun CI after posting a comment

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#90]
On some repositories, we can add a comment , for example "run CI" in order to relaunch a build. Because without this feature, we need to go the CI specific UI if we want to rebuild.  I o not know if behind this feature, we are using github / gitlab API or CI's one. But we can have a look.

**Comment by bastienterrier** [comment]
`git commit --allow-empty -m "rerun CI"`

**Comment by bastienterrier** [comment]
Waiting for a Github answer to add `base` and `head` data in its PullRequestComment Hook.

**Comment by bastienterrier** [comment]
Github Response:

> Hey there Bastien,
> 
> Thanks for writing in and I hope you are having a great day where you are.
> 
> Currently we have a single IssueComment event that encompasses both issues and pull requests, as listed here: https://developer.github.com/v3/activity/events/types/#issuecommentevent this reacts to the issue comment object, handled via the comments API, we document that this encompasses both issues and PRs here: https://developer.github.com/v3/issues/comments/.
> 
> I don't see that we have any plans currently to modify or introduce new hooks surrounding this. I will however feed back this feature request to the product team to take a look and see what we can do going forwards. As you can imagine we don't have a timeline for if or when we'll introduce these changes. For now your approach of using the number to load the relevant PR and fetch this information is the best workaround.
> 
> Thanks
> Matt Barber

**Comment by bastienterrier** [comment]
Cannot create empty commit with Gitlab or Github API
